# Generated by Django 5.1.7 on 2025-05-12 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('imageUrl', models.URLField()),
                ('release_date', models.CharField(max_length=4)),
                ('runtime', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('overview', models.TextField()),
                ('secondaryImage', models.URLField(blank=True, null=True)),
                ('trailerLink', models.URLField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('actors', models.CharField(blank=True, max_length=255, null=True)),
                ('awards', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_dates', to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=10)),
                ('language', models.CharField(default='Español', max_length=20)),
                ('availableSeats', models.IntegerField(default=100)),
                ('show_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_times', to='movies.showdate')),
            ],
        ),
    ]
